# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Дефолтный настройки
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # Настройки PEP-8. Проверяет длину строки и указан на версию python3.9, так же проверяет на пробелы
  - repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3.9
        args: [ "--line-length=120", "--target-version=py39" ]
  # Настройка длины текста и комментарий, игнорировать пробелы после ":" и разрыв строки перед бинарным
  # оператором
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-tidy-imports
          - flake8-typing-imports
        language_version: python3
        args: ["--max-line-length=120", "--max-doc-length=110", "--ignore=E203,W503,F401,F403" ]
  # Проверка на логическое наименование ветки в Гите
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: no-commit-to-branch
        args: ['--pattern=develop|main|master|^(?!((fix|feature)\/[a-zA-Z0-9\-]+)$).*']
  # Удаляет неиспользуемые импорты и переменные
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [ "--in-place", "--remove-unused-variables"]  # , "--remove-all-unused-imports" ]
  # Для сортировки импорта в алфавитном порядке, --src это путь к вашим исходным кодам
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [ "--line-length=120", "--src=src" ]
  # Обнаруживает ошибки программирования и выдает предложения по изменению кода в соответствии сPEP8
  - repo: https://github.com/PyCQA/pylint
    rev: v2.13.4
    hooks:
      - id: pylint
        args: [ "--disable=unused-argument" ]
  # Выполняет статическую проверку типов для my-py
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args: [ "--ignore-missing-imports" ]
        additional_dependencies:
          - types-requests
  # Проверки строк документации, требуется, проверка: чтобы первая строка строки документации была строкой
  # сводки и должна начинаться с повелительного глагола и заканчиваться точкой
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: [ "--ignore=E203,D100,D101,D102,D106,D203" ]
  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python manage.py test
        always_run: true
        pass_filenames: false
        language: system
  # Для созданий миграций
  - repo: https://github.com/remastr/pre-commit-django-check-migrations
    rev: v0.1.0
    hooks:
      - id: check-migrations-created
        args: [--manage-path=manage.py]
        additional_dependencies: [ django==3.2 ]
