repos:
  # Дефолтный настройки
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: debug-statements
      - id: name-tests-test
        args: ['--django']
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.10
        args: [ "--line-length=160", "--target-version=py39" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--max-line-length=160", "--max-doc-length=140", "--ignore=E203,W503,F401,F403"]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: [ "--ignore=E203,D100,D101,D102,D106,D103,D104,D105,D107,D203,D212,D408,D413" ]
  - repo: local
    hooks:
    - id: migrations-check
      language: system
      name: Check for uncreated migrations.
      entry: python3 manage.py makemigrations --check --dry-run
      types: ["python"]
      pass_filenames: false
  - repo: local
    hooks:
      - id: django-test
        language: system
        name: django-test
        entry: python3 manage.py test
        types: ["python"]
        always_run: true
        pass_filenames: false
